Sprint2
KAIFOLOV/frontend-courses pull request #2
Opened 2023-04-08 15:58 UTC by KAIFOLOV

2023-04-09 17:49 UTC, euge-huge commented
Смогу проверить ПР, только после того, как в этом ПР: https://github.com/KAIFOLOV/frontend-courses/pull/1 исправишь замечания и нажмешь в нем на кнопку Merge
<img width="304" alt="image" src="https://user-images.githubusercontent.com/58856916/230788358-b94ba9ec-dcf8-4c82-ba2f-bbef510b5d4a.png">

После чего, нужно будет переключиться на ветку sprint2 и сделать merge ветки master, вероятно могут быть конфликты при этом, это будет хорошая практика, чтобы научиться их решать! =)

2023-04-09 17:51 UTC, euge-huge requested changes
После того как все будет сделано, нужно будет нажать в этом ПР на кнопку re-review 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/58856916/230788534-1a19bbfc-6df9-473a-86bd-2df90fea2b49.png">

Тогда я снова увижу ПР на ревью и смогу его проверить

2023-04-13 05:28 UTC, KAIFOLOV commented
Объясните пожалуйста, что я не так сделал с gitignore

2023-04-13 14:47 UTC, euge-huge commented
C gitignore было все сделано правильно, она попала в исключения, но так как в репозиторий эта папка все же уже попала, то ее нужно было удалить, закоммитить эти изменения и вуоля, готово, ничего лишнего в репозитории нет :)

2023-04-13 15:11 UTC, euge-huge approved these changes
Работа получилась хорошая!

Замечаний немного, но они есть, касаются в основном scss.

Адаптив в шапке реализован, нужно будет доработать в других блоках в след. спринте)

Продолжай развиваться и улучшать код! С:

2023-04-13 15:11 UTC, euge-huge commented on src/index.html
`отлично`

Код выглядит презентабельно, лайк!

Хорошая структура и форматирование

2023-04-13 15:11 UTC, euge-huge commented on src/scss/_media.scss
> +  }
`можно лучше`

От пустых блоков лучше избавляться)

2023-04-13 15:11 UTC, euge-huge commented on src/scss/_media.scss
> +  }
Тоже можно убрать, если не нужен.

2023-04-13 15:11 UTC, euge-huge commented on src/scss/styles.scss
> +@import 'media';
`можно лучше`

Импорты лучше в самое начало файла вставлять, так их можно и не заметить)

2023-04-13 15:11 UTC, euge-huge commented on src/scss/styles.scss
`нужно поправить` `критично`

Код получился довольно хаотичным, предлагаю привести его в порядок :)
Совершенно не использована возможность нейминга в SCSS. SCSS позволяет вкладывать блоки в друг друга, этим обязательно нужно пользовтаься.
А учитывая что мы используем БЭМ, то это просто необходимо.

Поэтому как примерно может выглядеть блок с БЭМ и scss (пример):

```
.footer {
  &__title {
    &_main {}
    &_description {}
  }

 &__navigation {
    &__item {
      &:hover {...}
    }
  }
}
```

2023-04-13 15:11 UTC, euge-huge commented on src/scss/styles.scss
> +      }
`можно лучше`

На мой взгляд это всегда выбивает из контекста scss, лучше задать класс

2023-04-13 15:11 UTC, euge-huge commented on src/scss/styles.scss
> +    .social-network img,a:not(:first-child) {
Довольно сложно читается такая конструкция, лучше внести внутрь блока или как-то разбить

2023-04-13 15:11 UTC, euge-huge commented on src/scss/styles.scss
> +      }
`нужно поправить`

Вот тут, например, нужно поправить на что то типо:

```
.navigation {
  &__list {}
  &__link {
    &:hover {}
  }
}
```

И так по всему файлу! =)

2023-04-13 15:11 UTC, euge-huge commented on src/scss/styles.scss
> +      }
Можно вынести кнопки в отдельный блок где-нибудь в фале и сделать:

```
.button {
  &_large {}
}
```

Так неплохо делать (выносить) с элементами, которые часто повторяются на странице.

2023-04-13 15:11 UTC, euge-huge commented on src/scss/styles.scss
> +          font-weight: 400;
Тоже, везде советую поправить все для scss

2023-04-13 15:11 UTC, euge-huge commented on src/scss/styles.scss
> +      .section__card-master-img1 {
К таким названиям лучше не привыкать, выбирать что-то более понятное)

2023-04-16 17:13 UTC, KAIFOLOV commented on src/scss/styles.scss
> +      }
А можете объяснить почему так: вынес в отдельный файл

.button {
  .button_large {}
}

И стили не применяются, а вот с такой записью применяется, как это работает внутри

.button {
  &_large {}
}

2023-04-19 18:13 UTC, merged